name: Auto Sync Deploy Repo

on:
  push:
    branches:
      - master   

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4

      - name: Clone Deploy Repo
        run: |
          git clone https://x-access-token:${{ secrets.DEPLOY_REPO_TOKEN }}@github.com/ranadiveabhishek2001-creator/EDR_Project_Deploy_Test.git deploy

      - name: Copy Code (Replace only, no delete)
        run: |
          rsync -av --exclude '.git' ./ deploy/

      - name: Push Changes
        run: |
          cd deploy
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto sync from master branch" || echo "No changes to commit"
          git push origin HEAD:Saas