using MediatR;
using Microsoft.Extensions.Logging;
using NJS.Application.CQRS.Permissions.Commands;
using NJS.Application.Dtos;
using NJS.Domain.Entities;
using NJS.Repositories.Interfaces; // For IPermissionRepository, IRolePermissionRepository, IUnitOfWork
using NJS.Application.Services.IContract; // For ICurrentUserService, ITenantService
using System;
using System.Collections.Generic; // Added for List
using System.Linq; // Added for Any()
using System.Threading; // Added for CancellationToken
using System.Threading.Tasks;
using NJS.Domain.UnitWork;

namespace NJS.Application.CQRS.Permissions.Handlers
{
    public class CreatePermissionCommandHandler : IRequestHandler<CreatePermissionCommand, int>
    {
        private readonly IPermissionRepository _permissionRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICurrentUserService _currentUserService;
        private readonly ITenantService _tenantService; // Inject ITenantService
        private readonly ILogger<CreatePermissionCommandHandler> _logger;

        public CreatePermissionCommandHandler(
            IPermissionRepository permissionRepository,
            IUnitOfWork unitOfWork,
            ICurrentUserService currentUserService,
            ITenantService tenantService, // Add ITenantService parameter
            ILogger<CreatePermissionCommandHandler> logger)
        {
            _permissionRepository = permissionRepository ?? throw new ArgumentNullException(nameof(permissionRepository));
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
            _currentUserService = currentUserService ?? throw new ArgumentNullException(nameof(currentUserService));
            _tenantService = tenantService ?? throw new ArgumentNullException(nameof(tenantService)); // Assign ITenantService
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<int> Handle(CreatePermissionCommand request, CancellationToken cancellationToken)
        {
            if (request.PermissionDto == null)
            {
                _logger.LogError("CreatePermissionCommand received null PermissionDto.");
                throw new ArgumentNullException(nameof(request.PermissionDto));
            }

            // Basic validation: Check if a permission with the same name already exists
            var existingPermission = await _permissionRepository.GetByNameAsync(request.PermissionDto.Name);
            if (existingPermission != null)
            {
                _logger.LogWarning($"Permission with name '{request.PermissionDto.Name}' already exists.");
                throw new ArgumentException($"Permission with name '{request.PermissionDto.Name}' already exists.");
            }

            var permission = new Permission
            {
                Name = request.PermissionDto.Name,
                Description = request.PermissionDto.Description,
                Category = request.PermissionDto.Category
                // Note: Id is generated by the database
            };

            try
            {
                var createdPermissionId = await _permissionRepository.AddAsync(permission);
                _logger.LogInformation($"Permission created successfully with ID: {createdPermissionId}");

                // The logic for handling Role Permissions has been removed as IRolePermissionRepository is not available.
                // If this functionality is required, IRolePermissionRepository needs to be made available.

                return createdPermissionId;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating permission: {PermissionName}", request.PermissionDto.Name);
                // Rethrow the exception to be handled by global exception handling middleware
                throw;
            }
        }
    }
}
