-- WBSOptions.sql
-- Script to populate the WBSOptions table with predefined options for WBS levels

-- Check if WBSOptions table has data
IF EXISTS (SELECT TOP 1 1 FROM WBSOptions)
BEGIN
    PRINT 'WBSOptions table already has data, skipping insert';
END
ELSE
BEGIN
    PRINT 'WBSOptions table is empty, inserting data...';

    -- Insert Manpower Form Options (FormType 0)
    INSERT INTO WBSOptions (TenantId, Value, Label, Level, ParentId, FormType)
    VALUES 
    (1, 'inception_report', 'Inception Report', 1, NULL, 0),
    (1, 'feasibility_report', 'Feasibility Report', 1, NULL, 0),
    (1, 'draft_detailed_project_report', 'Draft Detailed Project Report', 1, NULL, 0),
    (1, 'detailed_project_report', 'Detailed Project Report', 1, NULL, 0),
    (1, 'tendering_documents', 'Tendering Documents', 1, NULL, 0),
    (1, 'construction_supervision', 'Construction Supervision', 1, NULL, 0),
    (1, 'surveys', 'Surveys', 2, 1, 0),
    (1, 'design', 'Design', 2, 1, 0),
    (1, 'cost_estimation', 'Cost Estimation', 2, 1, 0),
    (1, 'surveys', 'Surveys', 2, 2, 0),
    (1, 'design', 'Design', 2, 2, 0),
    (1, 'cost_estimation', 'Cost Estimation', 2, 2, 0),
    (1, 'surveys', 'Surveys', 2, 3, 0),
    (1, 'design', 'Design', 2, 3, 0),
    (1, 'cost_estimation', 'Cost Estimation', 2, 3, 0),
    (1, 'surveys', 'Surveys', 2, 4, 0),
    (1, 'design', 'Design', 2, 4, 0),
    (1, 'cost_estimation', 'Cost Estimation', 2, 4, 0),
    (1, 'surveys', 'Surveys', 2, 5, 0),
    (1, 'design', 'Design', 2, 5, 0),
    (1, 'cost_estimation', 'Cost Estimation', 2, 5, 0),
    (1, 'surveys', 'Surveys', 2, 6, 0),
    (1, 'design', 'Design', 2, 6, 0),
    (1, 'cost_estimation', 'Cost Estimation', 2, 6, 0),
    (1, 'topographical_survey', 'Topographical Survey', 3, 7, 0),
    (1, 'soil_investigation', 'Soil Investigation', 3, 7, 0),
    (1, 'social_impact_assessment', 'Social Impact Assessment', 3, 7, 0),
    (1, 'environmental_assessment', 'Environmental Assessment', 3, 7, 0),
    (1, 'flow_measurement', 'Flow Measurement', 3, 7, 0),
    (1, 'water_quality_measurement', 'Water Quality Measurement', 3, 7, 0),
    (1, 'process_design', 'Process Design', 3, 8, 0),
    (1, 'mechanical_design', 'Mechanical Design', 3, 8, 0),
    (1, 'structural_design', 'Structural Design', 3, 8, 0),
    (1, 'electrical_design', 'Electrical Design', 3, 8, 0),
    (1, 'ica_design', 'ICA Design', 3, 8, 0),
    (1, 'cost_estimation', 'Cost Estimation', 3, 9, 0),
    (1, 'topographical_survey', 'Topographical Survey', 3, 10, 0),
    (1, 'soil_investigation', 'Soil Investigation', 3, 10, 0),
    (1, 'social_impact_assessment', 'Social Impact Assessment', 3, 10, 0),
    (1, 'environmental_assessment', 'Environmental Assessment', 3, 10, 0),
    (1, 'flow_measurement', 'Flow Measurement', 3, 10, 0),
    (1, 'water_quality_measurement', 'Water Quality Measurement', 3, 10, 0),
    (1, 'process_design', 'Process Design', 3, 11, 0),
    (1, 'mechanical_design', 'Mechanical Design', 3, 11, 0),
    (1, 'structural_design', 'Structural Design', 3, 11, 0),
    (1, 'electrical_design', 'Electrical Design', 3, 11, 0),
    (1, 'ica_design', 'ICA Design', 3, 11, 0),
    (1, 'cost_estimation', 'Cost Estimation', 3, 12, 0),
    (1, 'topographical_survey', 'Topographical Survey', 3, 13, 0),
    (1, 'soil_investigation', 'Soil Investigation', 3, 13, 0),
    (1, 'social_impact_assessment', 'Social Impact Assessment', 3, 13, 0),
    (1, 'environmental_assessment', 'Environmental Assessment', 3, 13, 0),
    (1, 'flow_measurement', 'Flow Measurement', 3, 13, 0),
    (1, 'water_quality_measurement', 'Water Quality Measurement', 3, 13, 0),
    (1, 'process_design', 'Process Design', 3, 14, 0),
    (1, 'mechanical_design', 'Mechanical Design', 3, 14, 0),
    (1, 'structural_design', 'Structural Design', 3, 14, 0),
    (1, 'electrical_design', 'Electrical Design', 3, 14, 0),
    (1, 'ica_design', 'ICA Design', 3, 14, 0),
    (1, 'cost_estimation', 'Cost Estimation', 3, 15, 0),
    (1, 'topographical_survey', 'Topographical Survey', 3, 16, 0),
    (1, 'soil_investigation', 'Soil Investigation', 3, 16, 0),
    (1, 'social_impact_assessment', 'Social Impact Assessment', 3, 16, 0),
    (1, 'environmental_assessment', 'Environmental Assessment', 3, 16, 0),
    (1, 'flow_measurement', 'Flow Measurement', 3, 16, 0),
    (1, 'water_quality_measurement', 'Water Quality Measurement', 3, 16, 0),
    (1, 'process_design', 'Process Design', 3, 17, 0),
    (1, 'mechanical_design', 'Mechanical Design', 3, 17, 0),
    (1, 'structural_design', 'Structural Design', 3, 17, 0),
    (1, 'electrical_design', 'Electrical Design', 3, 17, 0),
    (1, 'ica_design', 'ICA Design', 3, 17, 0),
    (1, 'cost_estimation', 'Cost Estimation', 3, 18, 0),
    (1, 'topographical_survey', 'Topographical Survey', 3, 19, 0),
    (1, 'soil_investigation', 'Soil Investigation', 3, 19, 0),
    (1, 'social_impact_assessment', 'Social Impact Assessment', 3, 19, 0),
    (1, 'environmental_assessment', 'Environmental Assessment', 3, 19, 0),
    (1, 'flow_measurement', 'Flow Measurement', 3, 19, 0),
    (1, 'water_quality_measurement', 'Water Quality Measurement', 3, 19, 0),
    (1, 'process_design', 'Process Design', 3, 20, 0),
    (1, 'mechanical_design', 'Mechanical Design', 3, 20, 0),
    (1, 'structural_design', 'Structural Design', 3, 20, 0),
    (1, 'electrical_design', 'Electrical Design', 3, 20, 0),
    (1, 'ica_design', 'ICA Design', 3, 20, 0),
    (1, 'cost_estimation', 'Cost Estimation', 3, 21, 0),
    (1, 'topographical_survey', 'Topographical Survey', 3, 22, 0),
    (1, 'soil_investigation', 'Soil Investigation', 3, 22, 0),
    (1, 'social_impact_assessment', 'Social Impact Assessment', 3, 22, 0),
    (1, 'environmental_assessment', 'Environmental Assessment', 3, 22, 0),
    (1, 'flow_measurement', 'Flow Measurement', 3, 22, 0),
    (1, 'water_quality_measurement', 'Water Quality Measurement', 3, 22, 0),
    (1, 'process_design', 'Process Design', 3, 23, 0),
    (1, 'mechanical_design', 'Mechanical Design', 3, 23, 0),
    (1, 'structural_design', 'Structural Design', 3, 23, 0),
    (1, 'electrical_design', 'Electrical Design', 3, 23, 0),
    (1, 'ica_design', 'ICA Design', 3, 23, 0),
    (1, 'cost_estimation', 'Cost Estimation', 3, 24, 0);

    -- Insert ODC Form Options (FormType 1)
    INSERT INTO WBSOptions (TenantId, Value, Label, Level, ParentId, FormType)
    VALUES
    (1, 'general_odcs', 'General ODCS', 1, NULL, 1),
    (1, 'odcs_feasibility_report', 'ODCs Feasibility Report', 1, NULL, 1),
    (1, 'odcs_draft_dpr', 'ODCS Draft DPR', 1, NULL, 1),
    (1, 'travel', 'Travel', 2, 97, 1),
    (1, 'subsistence', 'Subsistence', 2, 97, 1),
    (1, 'local_conveyance', 'Local Conveyance', 2, 97, 1),
    (1, 'communications', 'Communications', 2, 97, 1),
    (1, 'office', 'Office', 2, 97, 1),
    (1, 'stationery_and_printing', 'Stationery and Printing', 2, 97, 1),
    (1, 'travel_1', 'Travel 1', 3, 100, 1),
    (1, 'travel_2', 'Travel 2', 3, 100, 1),
    (1, 'travel_3', 'Travel 3', 3, 100, 1),
    (1, 'travel_4', 'Travel 4', 3, 100, 1),
    (1, 's1', 'S1', 3, 101, 1),
    (1, 's2', 'S2', 3, 101, 1),
    (1, 's3', 'S3', 3, 101, 1),
    (1, 'car_1', 'Car 1', 3, 102, 1),
    (1, 'cell_phones', 'Cell Phones', 3, 103, 1),
    (1, 'internet', 'Internet', 3, 103, 1),
    (1, 'office_1', 'Office 1', 3, 104, 1),
    (1, 'printing', 'Printing', 3, 105, 1),
    (1, 'photocopy', 'Photocopy', 3, 105, 1),
    (1, 'topographical_surveys', 'Topographical Surveys', 2, 98, 1),
    (1, 'alignment_survey', 'Alignment Survey', 3, 119, 1),
    (1, 'plan_table_survey', 'Plan Table Survey', 3, 119, 1),
    (1, 'geotechnical_surveys', 'Geotechnical Surveys', 2, 99, 1),
    (1, 'water_quality_survey', 'Water Quality Survey', 2, 99, 1),
    (1, 'flow_measurement', 'Flow Measurement', 2, 99, 1),
    (1, 'part_1', 'Part 1', 3, 122, 1),
    (1, 'part_2', 'Part 2', 3, 122, 1),
    (1, 'part_3', 'Part 3', 3, 122, 1),
    (1, 'part_4', 'Part 4', 3, 122, 1),
    (1, 'wq1', 'WQ1', 3, 123, 1),
    (1, 'fm1', 'Fm1', 3, 124, 1);

    PRINT 'WBSOptions data inserted successfully';
    -- Verify the data was inserted
    SELECT * FROM WBSOptions ORDER BY FormType, Level, Value;
END
