export enum PermissionType {
    // Project Permissions
    VIEW_PROJECT = 'VIEW_PROJECT',
    CREATE_PROJECT = 'CREATE_PROJECT',
    EDIT_PROJECT = 'EDIT_PROJECT',
    DELETE_PROJECT = 'DELETE_PROJECT',
    REVIEW_PROJECT = 'REVIEW_PROJECT',
    APPROVE_PROJECT = 'APPROVE_PROJECT',
    SUBMIT_PROJECT_FOR_REVIEW = 'SUBMIT_PROJECT_FOR_REVIEW',
    SUBMIT_PROJECT_FOR_APPROVAL = 'SUBMIT_PROJECT_FOR_APPROVAL',
  
    // Business Development Permissions
    VIEW_BUSINESS_DEVELOPMENT = 'VIEW_BUSINESS_DEVELOPMENT',
    CREATE_BUSINESS_DEVELOPMENT = 'CREATE_BUSINESS_DEVELOPMENT',
    EDIT_BUSINESS_DEVELOPMENT = 'EDIT_BUSINESS_DEVELOPMENT',
    DELETE_BUSINESS_DEVELOPMENT = 'DELETE_BUSINESS_DEVELOPMENT',
    REVIEW_BUSINESS_DEVELOPMENT = 'REVIEW_BUSINESS_DEVELOPMENT',
    APPROVE_BUSINESS_DEVELOPMENT = 'APPROVE_BUSINESS_DEVELOPMENT',
    //SUBMIT_FOR_REVIEW = 'SUBMIT_FOR_REVIEW',
    SUBMIT_FOR_APPROVAL = 'SUBMIT_FOR_APPROVAL',
  
    // System Permissions
    SYSTEM_ADMIN = 'SYSTEM_ADMIN',
    TENANT_ADMIN = 'Tenant_ADMIN'
  }