using EDR.Domain.Entities;
using EDR.Domain.GenericRepository;
using EDR.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace EDR.Repositories.Repositories
{
    public class PermissionRepository : IPermissionRepository
    {
        private readonly IRepository<Permission> _repository;

        public PermissionRepository(IRepository<Permission> repository)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        }

        public async Task<IEnumerable<Permission>> GetAllAsync()
        {
            return await _repository.GetAllAsync().ConfigureAwait(false);
        }

        public async Task<Permission?> GetByIdAsync(int id)
        {
            return await _repository.GetByIdAsync(id).ConfigureAwait(false);
        }

        public async Task<int> AddAsync(Permission permission)
        {
            await _repository.AddAsync(permission).ConfigureAwait(false);
            await _repository.SaveChangesAsync().ConfigureAwait(false);
            return permission.Id; // Assuming Id is generated by the database and available after SaveChangesAsync
        }

        public async Task UpdateAsync(Permission permission)
        {
            await _repository.UpdateAsync(permission).ConfigureAwait(false);
            await _repository.SaveChangesAsync().ConfigureAwait(false); // Ensure changes are saved
        }

        public async Task DeleteAsync(int id)
        {
            var permission = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (permission != null)
            {
                await _repository.RemoveAsync(permission).ConfigureAwait(false);
                await _repository.SaveChangesAsync().ConfigureAwait(false); // Ensure changes are saved
            }
        }

        public async Task<Permission?> GetByNameAsync(string name)
        {
            var query = _repository.Query();
            return await query.FirstOrDefaultAsync(p => p.Name == name).ConfigureAwait(false);
        }

        public async Task<IEnumerable<Permission>> GetPermissionsByCategoryAsync(string category)
        {
            var query = _repository.Query();
            return await query.Where(p => p.Category == category)
                .ToListAsync()
                .ConfigureAwait(false);
        }

        public async Task<IEnumerable<Permission>> GetPermissionsByRoleIdAsync(string roleId)
        {
            var query = _repository.Query();
            return await query.Include(p => p.RolePermissions)
                .Where(p => p.RolePermissions.Any(rp => rp.RoleId == roleId))
                .ToListAsync()
                .ConfigureAwait(false);
        }
    }
}

