using MediatR;
using NJS.Application.CQRS.SprintTasks.Commands;
using NJS.Domain.Database;
using NJS.Domain.Entities;
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace NJS.Application.CQRS.SprintTasks.Handlers
{
    public class CreateSprintSubtaskCommandHandler : IRequestHandler<CreateSprintSubtaskCommand, int>
    {
        private readonly ProjectManagementContext _context;
        private readonly ILogger<CreateSprintSubtaskCommandHandler> _logger;

        public CreateSprintSubtaskCommandHandler(ProjectManagementContext context, ILogger<CreateSprintSubtaskCommandHandler> logger)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<int> Handle(CreateSprintSubtaskCommand request, CancellationToken cancellationToken)
        {
            var sprintSubtaskDto = request.SprintSubtask;

            if (sprintSubtaskDto == null || string.IsNullOrWhiteSpace(sprintSubtaskDto.Subtasktitle))
            {
                _logger.LogError("SprintSubtaskDto or Subtasktitle is null or empty in the request.");
                throw new ArgumentException("SprintSubtask or Subtasktitle cannot be null or empty.");
            }

            // Ensure TaskId is provided and exists before creating a subtask
            if (string.IsNullOrWhiteSpace(sprintSubtaskDto.Taskid))
            {
                _logger.LogError("TaskId is null or empty for SprintSubtask. It is required to associate a subtask with a parent task.");
                throw new ArgumentException("TaskId cannot be null or empty for SprintSubtask.");
            }

            var sprintTaskExists = await _context.SprintTasks.AnyAsync(st => st.Taskid == sprintSubtaskDto.Taskid, cancellationToken);
            if (!sprintTaskExists)
            {
                _logger.LogError("SprintTask with ID {TaskId} not found for SprintSubtask. Subtask cannot be created without a valid parent task.", sprintSubtaskDto.Taskid);
                throw new ArgumentException($"SprintTask with ID {sprintSubtaskDto.Taskid} not found. Subtask cannot be created.");
            }

            var subtask = new SprintSubtask
            {
                Subtaskkey = sprintSubtaskDto.Subtaskkey,
                TenantId = _context.TenantId ?? 1,
                Subtasktitle = sprintSubtaskDto.Subtasktitle,
                Subtaskdescription = sprintSubtaskDto.Subtaskdescription,
                Subtaskpriority = sprintSubtaskDto.Subtaskpriority,
                Subtaskstatus = sprintSubtaskDto.Subtaskstatus,
                SubtaskAssineid = sprintSubtaskDto.SubtaskAssineid,
                SubtaskAssigneeName = sprintSubtaskDto.SubtaskAssigneeName,
                SubtaskAssigneeAvatar = sprintSubtaskDto.SubtaskAssigneeAvatar,
                SubtaskReporterId = sprintSubtaskDto.SubtaskReporterId,
                SubtaskReporterName = sprintSubtaskDto.SubtaskReporterName,
                SubtaskReporterAvatar = sprintSubtaskDto.SubtaskReporterAvatar,
                // SubtaskId is typically auto-generated by the database for new entities.
                // Do not set it explicitly here.
                Attachments = sprintSubtaskDto.Attachments,
                SubtaskisExpanded = sprintSubtaskDto.SubtaskisExpanded,
                SubtaskcreatedDate = sprintSubtaskDto.SubtaskcreatedDate ?? DateTime.UtcNow,
                SubtaskupdatedDate = sprintSubtaskDto.SubtaskupdatedDate ?? DateTime.UtcNow,
                SubtaskType = sprintSubtaskDto.SubtaskType,
                Taskid = sprintSubtaskDto.Taskid, // Foreign key to SprintTask
                DisplayOrder = sprintSubtaskDto.DisplayOrder ?? 0,
                EstimatedHours = sprintSubtaskDto.EstimatedHours ?? 0,
                ActualHours = sprintSubtaskDto.ActualHours ?? 0,
                StartedAt = sprintSubtaskDto.StartedAt,
                CompletedAt = sprintSubtaskDto.CompletedAt
            };

            await _context.SprintSubtasks.AddAsync(subtask, cancellationToken);
            var changesSaved = await _context.SaveChangesAsync(cancellationToken);

            _logger.LogInformation("SprintSubtask saved successfully. New Subtask ID: {SubtaskId} for Task ID: {TaskId}. Changes saved: {Changes}", subtask.SubtaskId, subtask.Taskid, changesSaved);

            return subtask.SubtaskId;
        }
    }
}
