// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NJS.Domain.Database;

#nullable disable

namespace NJS.Domain.Migrations
{
    [DbContext(typeof(ProjectManagementContext))]
    [Migration("20241113092431_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NJS.Domain.Entities.FeasibilityStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetitionAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinancialInformation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FundingStream")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProbabilityAssessment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("QualifyingCriteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrategicRanking")
                        .HasColumnType("int");

                    b.Property<DateTime>("StudyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("FeasibilityStudies");
                });

            modelBuilder.Entity("NJS.Domain.Entities.GoNoGoDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionPlan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidScheduleComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("BidScheduleScore")
                        .HasColumnType("int");

                    b.Property<string>("BidType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientRelationshipComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ClientRelationshipScore")
                        .HasColumnType("int");

                    b.Property<string>("CompetitionAssessmentComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CompetitionAssessmentScore")
                        .HasColumnType("int");

                    b.Property<string>("CompetitivePositionComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CompetitivePositionScore")
                        .HasColumnType("int");

                    b.Property<string>("CompletedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DecisionComments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("EMDAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FinancialEligibilityComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FinancialEligibilityScore")
                        .HasColumnType("int");

                    b.Property<string>("FutureWorkPotentialComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FutureWorkPotentialScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MarketingPlanComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MarketingPlanScore")
                        .HasColumnType("int");

                    b.Property<string>("ProfitabilityComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProfitabilityScore")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectKnowledgeComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProjectKnowledgeScore")
                        .HasColumnType("int");

                    b.Property<string>("ResourceAvailabilityComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResourceAvailabilityScore")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StaffAvailabilityComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StaffAvailabilityScore")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalEligibilityComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TechnicalEligibilityScore")
                        .HasColumnType("int");

                    b.Property<decimal>("TenderFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("GoNoGoDecisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BidScheduleComments = "Timeline is achievable",
                            BidScheduleScore = 8,
                            BidType = "Lumpsum",
                            ClientRelationshipComments = "Good relationship with municipality",
                            ClientRelationshipScore = 7,
                            CompetitionAssessmentComments = "Limited competition in this sector",
                            CompetitionAssessmentScore = 8,
                            CompetitivePositionComments = "Strong market position",
                            CompetitivePositionScore = 8,
                            CompletedBy = "System",
                            CompletedDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            DecisionComments = "Project aligns with our expertise",
                            EMDAmount = 100000m,
                            FinancialEligibilityComments = "Strong financial position",
                            FinancialEligibilityScore = 8,
                            FutureWorkPotentialComments = "High potential for similar projects",
                            FutureWorkPotentialScore = 9,
                            MarketingPlanComments = "Strong marketing strategy in water sector",
                            MarketingPlanScore = 8,
                            ProfitabilityComments = "Good profit margins expected",
                            ProfitabilityScore = 8,
                            ProjectId = 1,
                            ProjectKnowledgeComments = "Extensive experience in water supply projects",
                            ProjectKnowledgeScore = 8,
                            ResourceAvailabilityComments = "Resources can be allocated",
                            ResourceAvailabilityScore = 7,
                            Sector = "Water",
                            StaffAvailabilityComments = "Required staff available",
                            StaffAvailabilityScore = 7,
                            Status = 0,
                            TechnicalEligibilityComments = "Meets all technical requirements",
                            TechnicalEligibilityScore = 9,
                            TenderFee = 5000m,
                            TotalScore = 95
                        },
                        new
                        {
                            Id = 2,
                            BidScheduleComments = "Timeline manageable",
                            BidScheduleScore = 7,
                            BidType = "EPC",
                            ClientRelationshipComments = "Strong relationship with authority",
                            ClientRelationshipScore = 8,
                            CompetitionAssessmentComments = "Moderate competition",
                            CompetitionAssessmentScore = 7,
                            CompetitivePositionComments = "Good market position",
                            CompetitivePositionScore = 7,
                            CompletedBy = "System",
                            CompletedDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            DecisionComments = "Proceed with careful resource planning",
                            EMDAmount = 150000m,
                            FinancialEligibilityComments = "Financially capable",
                            FinancialEligibilityScore = 8,
                            FutureWorkPotentialComments = "Potential for future smart city projects",
                            FutureWorkPotentialScore = 8,
                            MarketingPlanComments = "Developing marketing strategy",
                            MarketingPlanScore = 7,
                            ProfitabilityComments = "Acceptable profit margins",
                            ProfitabilityScore = 7,
                            ProjectId = 4,
                            ProjectKnowledgeComments = "Good understanding of requirements",
                            ProjectKnowledgeScore = 7,
                            ResourceAvailabilityComments = "Resource planning required",
                            ResourceAvailabilityScore = 6,
                            Sector = "Smart City",
                            StaffAvailabilityComments = "Some resource allocation needed",
                            StaffAvailabilityScore = 6,
                            Status = 1,
                            TechnicalEligibilityComments = "Meets technical criteria",
                            TechnicalEligibilityScore = 8,
                            TenderFee = 7500m,
                            TotalScore = 86
                        },
                        new
                        {
                            Id = 3,
                            BidScheduleComments = "Timeline challenging",
                            BidScheduleScore = 6,
                            BidType = "Design-Build",
                            ClientRelationshipComments = "New client relationship",
                            ClientRelationshipScore = 6,
                            CompetitionAssessmentComments = "Strong competition in sector",
                            CompetitionAssessmentScore = 5,
                            CompetitivePositionComments = "Limited competitive advantage",
                            CompetitivePositionScore = 5,
                            CompletedBy = "System",
                            CompletedDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            DecisionComments = "Project risks outweigh potential benefits",
                            EMDAmount = 90000m,
                            FinancialEligibilityComments = "Financial requirements met",
                            FinancialEligibilityScore = 7,
                            FutureWorkPotentialComments = "Moderate future potential",
                            FutureWorkPotentialScore = 6,
                            MarketingPlanComments = "Limited market presence in coastal sector",
                            MarketingPlanScore = 5,
                            ProfitabilityComments = "Low profit margins expected",
                            ProfitabilityScore = 5,
                            ProjectId = 5,
                            ProjectKnowledgeComments = "Limited experience in coastal projects",
                            ProjectKnowledgeScore = 5,
                            ResourceAvailabilityComments = "Significant resource gaps",
                            ResourceAvailabilityScore = 4,
                            Sector = "Coastal",
                            StaffAvailabilityComments = "Resource constraints identified",
                            StaffAvailabilityScore = 4,
                            Status = 2,
                            TechnicalEligibilityComments = "Some technical gaps identified",
                            TechnicalEligibilityScore = 6,
                            TenderFee = 4500m,
                            TotalScore = 64
                        });
                });

            modelBuilder.Entity("NJS.Domain.Entities.OpportunityTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BidFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BidManager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPersonAtClient")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateOfResult")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfSubmission")
                        .HasColumnType("date");

                    b.Property<decimal?>("EMD")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FollowUpComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FormOfEMD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GrossRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LikelyCompetition")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal?>("NetNJSRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("PercentageChanceOfNJSSuccess")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PercentageChanceOfProjectHappening")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProbableQualifyingCriteria")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StrategicRanking")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TrackedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("OpportunityTrackings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BidFees = 75000m,
                            BidManager = "John Smith",
                            ContactPersonAtClient = "Rajesh Kumar",
                            CreatedAt = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            DateOfSubmission = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMD = 150000m,
                            FollowUpComments = "Client very interested in smart solutions",
                            FormOfEMD = "Bank Guarantee",
                            GrossRevenue = 7500000m,
                            LastModifiedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = "System",
                            LikelyCompetition = "L&T, HCC, Gammon",
                            Month = 11,
                            NetNJSRevenue = 6000000m,
                            Notes = "Need to focus on IoT integration",
                            PercentageChanceOfNJSSuccess = 65.0m,
                            PercentageChanceOfProjectHappening = 75.5m,
                            ProbableQualifyingCriteria = "Similar project experience, Local presence",
                            ProjectId = 2,
                            Stage = "B",
                            StrategicRanking = "H",
                            TrackedBy = "System",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            BidFees = 50000m,
                            BidManager = "Sarah Johnson",
                            ContactPersonAtClient = "Amit Patel",
                            CreatedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            DateOfSubmission = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMD = 100000m,
                            FollowUpComments = "Technical presentation scheduled",
                            FormOfEMD = "Bank Draft",
                            GrossRevenue = 3200000m,
                            LastModifiedAt = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = "System",
                            LikelyCompetition = "Tata Projects, SPML Infra",
                            Month = 11,
                            NetNJSRevenue = 2500000m,
                            Notes = "Focus on flood prediction systems",
                            PercentageChanceOfNJSSuccess = 55.0m,
                            PercentageChanceOfProjectHappening = 60.0m,
                            ProbableQualifyingCriteria = "Similar project experience, Local presence",
                            ProjectId = 3,
                            Stage = "A",
                            StrategicRanking = "M",
                            TrackedBy = "System",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            BidFees = 50000m,
                            BidManager = "John Johnson",
                            ContactPersonAtClient = "Amita Patel",
                            CreatedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            DateOfSubmission = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMD = 100000m,
                            FollowUpComments = "Technical presentation scheduled",
                            FormOfEMD = "Bank Draft",
                            GrossRevenue = 3200000m,
                            LastModifiedAt = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = "System",
                            LikelyCompetition = "Tata Projects, SPML Infra",
                            Month = 11,
                            NetNJSRevenue = 2500000m,
                            Notes = "Focus on flood prediction systems",
                            PercentageChanceOfNJSSuccess = 55.0m,
                            PercentageChanceOfProjectHappening = 60.0m,
                            ProbableQualifyingCriteria = "Similar project experience, Local presence",
                            ProjectId = 13,
                            Stage = "B",
                            StrategicRanking = "M",
                            TrackedBy = "System",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            BidFees = 50000m,
                            BidManager = "Sarah Johnson",
                            ContactPersonAtClient = "Amit Patel",
                            CreatedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            DateOfSubmission = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMD = 100000m,
                            FollowUpComments = "Technical presentation scheduled",
                            FormOfEMD = "Bank Draft",
                            GrossRevenue = 3200000m,
                            LastModifiedAt = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = "System",
                            LikelyCompetition = "Tata Projects, SPML Infra, ABC",
                            Month = 11,
                            NetNJSRevenue = 2500000m,
                            Notes = "Focus on flood prediction systems",
                            PercentageChanceOfNJSSuccess = 55.0m,
                            PercentageChanceOfProjectHappening = 60.0m,
                            ProbableQualifyingCriteria = "Similar project experience, Local presence",
                            ProjectId = 15,
                            Stage = "A",
                            StrategicRanking = "M",
                            TrackedBy = "System",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("NJS.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CapitalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientSector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FundingStream")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Metropolis Municipality",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 5000000m,
                            Name = "City Water Supply Upgrade",
                            Progress = 65,
                            Sector = "Water",
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 6
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "State Rural Development Dept",
                            ClientSector = "Government",
                            ContractType = "Design-Build",
                            CreatedAt = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 2000000m,
                            Name = "Rural Sanitation Initiative",
                            Progress = 25,
                            Sector = "Sanitation",
                            StartDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            ClientName = "Industrial Development Corp",
                            ClientSector = "Private",
                            ContractType = "Turnkey",
                            CreatedAt = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 3500000m,
                            Name = "Industrial Park Drainage System",
                            Progress = 100,
                            Sector = "Industrial",
                            StartDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            ClientName = "Smart City Development Authority",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EstimatedCost = 7500000m,
                            Name = "Smart City Water Management",
                            Progress = 0,
                            Sector = "Smart City",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            ClientName = "Maritime Development Board",
                            ClientSector = "Government",
                            ContractType = "Design-Build",
                            CreatedAt = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 4500000m,
                            Name = "Coastal Zone Protection",
                            Progress = 45,
                            Sector = "Coastal",
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            ClientName = "City Municipal Corporation",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EstimatedCost = 3200000m,
                            Name = "Urban Flood Management",
                            Progress = 0,
                            Sector = "Urban Infrastructure",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            ClientName = "Municipality",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 600000m,
                            Name = "Pune City Water Supply Upgrade",
                            Progress = 65,
                            Sector = "Water",
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 6
                        },
                        new
                        {
                            Id = 8,
                            ClientName = "Maharashtra Rural Development Dept",
                            ClientSector = "Government",
                            ContractType = "Design-Build",
                            CreatedAt = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 2000000m,
                            Name = "Rural Initiative",
                            Progress = 25,
                            Sector = "Sanitation",
                            StartDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            ClientName = "Industrial Development Corp",
                            ClientSector = "Private",
                            ContractType = "Turnkey",
                            CreatedAt = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 3500000m,
                            Name = "Industrial Park System",
                            Progress = 100,
                            Sector = "Industrial",
                            StartDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            ClientName = "Smart City Development Authority",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EstimatedCost = 7500000m,
                            Name = "City Water Management 2",
                            Progress = 0,
                            Sector = "Smart City",
                            Status = 4
                        },
                        new
                        {
                            Id = 11,
                            ClientName = "Maritime Development Board",
                            ClientSector = "Government",
                            ContractType = "Design-Build",
                            CreatedAt = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EndDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedCost = 4500000m,
                            Name = "Coastal Protection 2",
                            Progress = 45,
                            Sector = "Coastal",
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5
                        },
                        new
                        {
                            Id = 12,
                            ClientName = "City Municipal Corporation",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EstimatedCost = 3200000m,
                            Name = "Urban Management",
                            Progress = 0,
                            Sector = "Urban Infrastructure",
                            Status = 5
                        },
                        new
                        {
                            Id = 13,
                            ClientName = "City Municipal Corporation",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EstimatedCost = 3900000m,
                            Name = "Urban Management 23",
                            Progress = 0,
                            Sector = "Urban Infrastructure",
                            Status = 7
                        },
                        new
                        {
                            Id = 14,
                            ClientName = "State Industrial Development Corp",
                            ClientSector = "Government",
                            ContractType = "EPC",
                            CreatedAt = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EstimatedCost = 12500000m,
                            Name = "Mega Industrial Park",
                            Progress = 0,
                            Sector = "Industrial",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            ClientName = "National Highway Authority",
                            ClientSector = "Government",
                            ContractType = "Design-Build",
                            CreatedAt = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            EstimatedCost = 7800000m,
                            Name = "Expressway Stormwater Drainage",
                            Progress = 0,
                            Sector = "Transportation",
                            Status = 0
                        });
                });

            modelBuilder.Entity("NJS.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("NJS.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NJS.Domain.Entities.UserWBSTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WBSTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WBSTaskId");

                    b.ToTable("UserWBSTasks");
                });

            modelBuilder.Entity("NJS.Domain.Entities.WBSTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkBreakdownStructureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkBreakdownStructureId");

                    b.ToTable("WBSTasks");
                });

            modelBuilder.Entity("NJS.Domain.Entities.WorkBreakdownStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkBreakdownStructures");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("NJS.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NJS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NJS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("NJS.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NJS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NJS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NJS.Domain.Entities.FeasibilityStudy", b =>
                {
                    b.HasOne("NJS.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NJS.Domain.Entities.GoNoGoDecision", b =>
                {
                    b.HasOne("NJS.Domain.Entities.Project", "Project")
                        .WithOne("GoNoGoDecision")
                        .HasForeignKey("NJS.Domain.Entities.GoNoGoDecision", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NJS.Domain.Entities.OpportunityTracking", b =>
                {
                    b.HasOne("NJS.Domain.Entities.Project", "Project")
                        .WithMany("OpportunityTrackings")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NJS.Domain.Entities.UserWBSTask", b =>
                {
                    b.HasOne("NJS.Domain.Entities.User", "User")
                        .WithMany("UserWBSTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NJS.Domain.Entities.WBSTask", "WBSTask")
                        .WithMany("UserWBSTasks")
                        .HasForeignKey("WBSTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WBSTask");
                });

            modelBuilder.Entity("NJS.Domain.Entities.WBSTask", b =>
                {
                    b.HasOne("NJS.Domain.Entities.WorkBreakdownStructure", "WorkBreakdownStructure")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkBreakdownStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkBreakdownStructure");
                });

            modelBuilder.Entity("NJS.Domain.Entities.WorkBreakdownStructure", b =>
                {
                    b.HasOne("NJS.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NJS.Domain.Entities.Project", b =>
                {
                    b.Navigation("GoNoGoDecision");

                    b.Navigation("OpportunityTrackings");
                });

            modelBuilder.Entity("NJS.Domain.Entities.User", b =>
                {
                    b.Navigation("UserWBSTasks");
                });

            modelBuilder.Entity("NJS.Domain.Entities.WBSTask", b =>
                {
                    b.Navigation("UserWBSTasks");
                });

            modelBuilder.Entity("NJS.Domain.Entities.WorkBreakdownStructure", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
