import { Project} from "../../models"

const projectsData = {
  "1":{
    "id": "1",
    "name": "City Water Supply Upgrade",
    "details" : "City needs water supply upgrade", //
    "clientName": "Metropolis Municipality",
    "projectMangerId" : "usr1", //
    "office" : "Mumbai",// 
    "projectNo" : "abc-123", //
    "typeOfJob" : "Water Supply",
    "seniorProjectMangerId" : "usr1",
    "sector": "Water",
    "region" : "West",
    "typeOfClient": "Government",
    "estimatedCost": 5000000,
    "feeType" : "Lumpsum",
    "startDate": "2023-01-01",
    "endDate": "2024-12-31",
    "currency": "INR",
    "regionalManagerID": "usr6",
    "status": "Active",
    "priority": "Medium",
    "budget": 5000000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "2":{
    "id": "2",
    "name": "Rural Sanitation Initiative",
    "details": "Comprehensive sanitation upgrade for rural areas",
    "clientName": "State Rural Development Dept",
    "projectMangerId": "usr2",
    "office": "Delhi",
    "projectNo": "san-456",
    "typeOfJob": "Sanitation Infrastructure",
    "seniorProjectMangerId": "usr4",
    "sector": "Sanitation",
    "region": "North",
    "typeOfClient": "Government",
    "estimatedCost": 2000000,
    "feeType": "Itemrate",
    "startDate": "2023-03-15",
    "endDate": "2025-03-14",
    "currency": "INR",
    "regionalManagerID": "usr7",
    "status": "Active",
    "priority": "Medium",
    "budget": 2000000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "3":{
    "id": "3",
    "name": "Industrial Park Drainage System",
    "details": "Development of comprehensive drainage system for industrial park",
    "clientName": "Industrial Development Corp",
    "projectMangerId": "usr3",
    "office": "Pune",
    "projectNo": "ind-789",
    "typeOfJob": "Industrial Infrastructure",
    "seniorProjectMangerId": "usr5",
    "sector": "Industrial",
    "region": "West",
    "typeOfClient": "Private",
    "estimatedCost": 3500000,
    "feeType": "Lumpsum",
    "startDate": "2022-07-01",
    "endDate": "2023-12-31",
    "currency": "INR",
    "regionalManagerID": "usr6",
    "status": "Active",
    "priority": "Medium",
    "budget": 3500000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "4":{
    "id": "4",
    "name": "Smart City Water Management",
    "details": "Implementation of smart water management solutions",
    "clientName": "Smart City Development Authority",
    "projectMangerId": "usr2",
    "office": "Bangalore",
    "projectNo": "smt-101",
    "typeOfJob": "Smart Infrastructure",
    "seniorProjectMangerId": "usr4",
    "sector": "Smart City",
    "region": "South",
    "typeOfClient": "Government",
    "estimatedCost": 7500000,
    "feeType": "Itemrate",
    "startDate": "2023-11-01",
    "endDate": "2025-10-31",
    "currency": "INR",
    "regionalManagerID": "usr7",
    "status": "Active",
    "priority": "Medium",
    "budget": 7500000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "5":{
    "id": "5",
    "name": "Coastal Zone Protection",
    "details": "Coastal infrastructure protection and development",
    "clientName": "Maritime Development Board",
    "projectMangerId": "usr3",
    "office": "Chennai",
    "projectNo": "cst-202",
    "typeOfJob": "Coastal Protection",
    "seniorProjectMangerId": "usr5",
    "sector": "Coastal",
    "region": "South",
    "typeOfClient": "Government",
    "estimatedCost": 4500000,
    "feeType": "Lumpsum",
    "startDate": "2023-06-01",
    "endDate": "2025-05-31",
    "currency": "INR",
    "regionalManagerID": "usr6",
    "status": "Active",
    "priority": "Medium",
    "budget": 4500000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "6":{
    "id": "6",
    "name": "Urban Flood Management",
    "details": "Urban flood prevention and management system",
    "clientName": "City Municipal Corporation",
    "projectMangerId": "usr2",
    "office": "Kolkata",
    "projectNo": "ufl-303",
    "typeOfJob": "Flood Management",
    "seniorProjectMangerId": "usr4",
    "sector": "Urban Infrastructure",
    "region": "East",
    "typeOfClient": "Government",
    "estimatedCost": 3200000,
    "feeType": "Itemrate",
    "startDate": "2023-06-01",
    "endDate": "2025-05-31",
    "currency": "INR",
    "regionalManagerID": "usr7",
    "status": "Active",
    "priority": "Medium",
    "budget": 3200000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "7": {
    "id": "7",
    "name": "Pune City Water Supply Upgrade",
    "details": "Comprehensive water supply upgrade for Pune city",
    "clientName": "Municipality",
    "projectMangerId": "usr3",
    "office": "Pune",
    "projectNo": "pun-404",
    "typeOfJob": "Water Supply",
    "seniorProjectMangerId": "usr5",
    "sector": "Water",
    "region": "West",
    "typeOfClient": "Government",
    "estimatedCost": 600000,
    "feeType": "Lumpsum",
    "startDate": "2023-01-01",
    "endDate": "2024-12-31",
    "currency": "INR",
    "regionalManagerID": "usr6",
    "status": "Active",
    "priority": "Medium",
    "budget": 600000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "8": {
    "id": "8",
    "name": "Rural Initiative",
    "details": "Rural development and infrastructure improvement",
    "clientName": "Maharashtra Rural Development Dept",
    "projectMangerId": "usr2",
    "office": "Mumbai",
    "projectNo": "rur-505",
    "typeOfJob": "Rural Development",
    "seniorProjectMangerId": "usr4",
    "sector": "Sanitation",
    "region": "West",
    "typeOfClient": "Government",
    "estimatedCost": 2000000,
    "feeType": "Itemrate",
    "startDate": "2023-03-15",
    "endDate": "2025-03-14",
    "currency": "INR",
    "regionalManagerID": "usr7",
    "status": "Active",
    "priority": "Medium",
    "budget": 2000000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "9": {
    "id": "9",
    "name": "Industrial Park System",
    "details": "Industrial park infrastructure development",
    "clientName": "Industrial Development Corp",
    "projectMangerId": "usr3",
    "office": "Hyderabad",
    "projectNo": "ind-606",
    "typeOfJob": "Industrial Infrastructure",
    "seniorProjectMangerId": "usr5",
    "sector": "Industrial",
    "region": "South",
    "typeOfClient": "Private",
    "estimatedCost": 3500000,
    "feeType": "Lumpsum",
    "startDate": "2023-03-15",
    "endDate": "2025-03-14",
    "currency": "INR",
    "regionalManagerID": "usr6",
    "status": "Active",
    "priority": "Medium",
    "budget": 3500000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "10": {
    "id": "10",
    "name": "City Water Management 2",
    "details": "Smart water management system implementation",
    "clientName": "Smart City Development Authority",
    "projectMangerId": "usr2",
    "office": "Ahmedabad",
    "projectNo": "smt-707",
    "typeOfJob": "Smart Infrastructure",
    "seniorProjectMangerId": "usr4",
    "sector": "Smart City",
    "region": "West",
    "typeOfClient": "Government",
    "estimatedCost": 7500000,
    "feeType": "Itemrate",
    "startDate": "2023-06-01",
    "endDate": "2025-05-31",
    "currency": "INR",
    "regionalManagerID": "usr6",
    "status": "Active",
    "priority": "Medium",
    "budget": 7500000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "11": {
    "id": "11",
    "name": "Coastal Protection 2",
    "details": "Coastal area protection and development",
    "clientName": "Maritime Development Board",
    "projectMangerId": "usr3",
    "office": "Vizag",
    "projectNo": "cst-808",
    "typeOfJob": "Coastal Protection",
    "seniorProjectMangerId": "usr5",
    "sector": "Coastal",
    "region": "East",
    "typeOfClient": "Government",
    "estimatedCost": 4500000,
    "feeType": "Lumpsum",
    "startDate": "2023-06-01",
    "endDate": "2025-05-31",
    "currency": "INR",
    "regionalManagerID": "usr7",
    "status": "Active",
    "priority": "Medium",
    "budget": 4500000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "12": {
    "id": "12",
    "name": "Urban Management",
    "details": "Urban infrastructure management and development",
    "clientName": "City Municipal Corporation",
    "projectMangerId": "usr2",
    "office": "Lucknow",
    "projectNo": "urb-909",
    "typeOfJob": "Urban Development",
    "seniorProjectMangerId": "usr4",
    "sector": "Urban Infrastructure",
    "region": "North",
    "typeOfClient": "Government",
    "estimatedCost": 3200000,
    "feeType": "Itemrate",
    "startDate": "2023-06-01",
    "endDate": "2025-05-31",
    "currency": "INR",
    "regionalManagerID": "usr7",
    "status": "Active",
    "priority": "Medium",
    "budget": 3200000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "13": {
    "id": "13",
    "name": "Urban Management 23",
    "details": "Comprehensive urban management system",
    "clientName": "City Municipal Corporation",
    "projectMangerId": "usr3",
    "office": "Bhopal",
    "projectNo": "urb-1010",
    "typeOfJob": "Urban Development",
    "seniorProjectMangerId": "usr5",
    "sector": "Urban Infrastructure",
    "region": "Central",
    "typeOfClient": "Government",
    "estimatedCost": 3900000,
    "feeType": "Lumpsum",
    "startDate": "2023-11-15",
    "endDate": "2025-11-14",
    "currency": "INR",
    "regionalManagerID": "usr6",
    "status": "Active",
    "priority": "Medium",
    "budget": 3900000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "14": {
    "id": "14",
    "name": "Mega Industrial Park",
    "details": "Large-scale industrial park development",
    "clientName": "State Industrial Development Corp",
    "projectMangerId": "usr2",
    "office": "Nagpur",
    "projectNo": "ind-1111",
    "typeOfJob": "Industrial Infrastructure",
    "seniorProjectMangerId": "usr4",
    "sector": "Industrial",
    "region": "Central",
    "typeOfClient": "Government",
    "estimatedCost": 12500000,
    "feeType": "Itemrate",
    "startDate": "2023-12-01",
    "endDate": "2026-11-30",
    "currency": "INR",
    "regionalManagerID": "usr7",
    "status": "Active",
    "priority": "Medium",
    "budget": 12500000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  },
  "15": {
    "id": "15",
    "name": "Expressway Stormwater Drainage",
    "details": "Stormwater drainage system for expressway",
    "clientName": "National Highway Authority",
    "projectMangerId": "usr3",
    "office": "Gurgaon",
    "projectNo": "exp-1212",
    "typeOfJob": "Transportation Infrastructure",
    "seniorProjectMangerId": "usr5",
    "sector": "Transportation",
    "region": "North",
    "typeOfClient": "Government",
    "estimatedCost": 7800000,
    "feeType": "Lumpsum",
    "startDate": "2023-12-05",
    "endDate": "2025-12-04",
    "currency": "INR",
    "regionalManagerID": "usr12",
    "status": "Active",
    "priority": "Medium",
    "budget": 7800000,
    "createdAt": "2023-01-01",
    "updatedAt": "2023-01-01"
  }
} as const;

// Transform the JSON object into an array of Project type
export const projects: Project[] = Object.values(projectsData).map(project => ({
  ...project
}));

// Utility function to get a single project by ID
export const getProjectById = (id: string): Project | undefined => {
  return projects.find(project => project.id === id);
};

// Utility function to filter projects by sector
export const getProjectsBySector = (sector: string): Project[] => {
  return projects.filter(project => project.sector === sector);
};

// Utility function to calculate total project value
export const calculateTotalProjectValue = (): number => {
  return projects.reduce((sum, project) => sum + project.estimatedCost, 0);
};
