using MediatR;
using NJS.Application.CQRS.SprintPlans.Commands;
using NJS.Domain.Database;
using NJS.Domain.Entities;
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Linq; // Added for AnyAsync extension method
using Microsoft.EntityFrameworkCore; // Ensure this is present for extension methods
using Microsoft.Extensions.Logging;

namespace NJS.Application.CQRS.SprintPlans.Handlers
{
    public class CreateSingleSprintPlanCommandHandler : IRequestHandler<CreateSingleSprintPlanCommand, int>
    {
        private readonly ProjectManagementContext _context;
        private readonly ILogger<CreateSingleSprintPlanCommandHandler> _logger;

        public CreateSingleSprintPlanCommandHandler(ProjectManagementContext context, ILogger<CreateSingleSprintPlanCommandHandler> logger)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<int> Handle(CreateSingleSprintPlanCommand request, CancellationToken cancellationToken)
        {
            var sprintPlanDto = request.SprintPlan;

            if (sprintPlanDto == null || sprintPlanDto.ProjectId == 0)
            {
                _logger.LogError("SprintPlanDto or ProjectId is null or empty in the request.");
                throw new ArgumentException("SprintPlan or ProjectId cannot be null or empty.");
            }

            // Check if the project exists
            _logger.LogInformation("Checking if Project with ID {ProjectId} exists for SprintPlan.", sprintPlanDto.ProjectId);
            var projectExists = await _context.Projects.AnyAsync(p => p.Id == sprintPlanDto.ProjectId, cancellationToken);
            if (!projectExists)
            {
                _logger.LogError("Project with ID {ProjectId} not found for SprintPlan. Throwing ArgumentException.", sprintPlanDto.ProjectId);
                throw new ArgumentException($"Project with ID {sprintPlanDto.ProjectId} not found.");
            }
            _logger.LogInformation("Project with ID {ProjectId} exists for SprintPlan.", sprintPlanDto.ProjectId);

            // Create a new SprintPlan entity from the DTO
            var sprintPlan = new SprintPlan
            {
                SprintNumber = sprintPlanDto.SprintNumber,
                StartDate = sprintPlanDto.StartDate,
                EndDate = sprintPlanDto.EndDate,
                SprintGoal = sprintPlanDto.SprintGoal,
                ProjectId = sprintPlanDto.ProjectId,
                SprintEmployee = sprintPlanDto.SprintEmployee, // Map the new column
                TenantId = _context.TenantId ?? 1 // Assuming TenantId is handled by context
            };

            // SprintId is auto-generated by the database, so we don't set it from DTO on creation
            // SprintTasks and SprintSubtasks are NOT handled by this API, as per requirement.

            await _context.SprintPlans.AddAsync(sprintPlan, cancellationToken);
            var changesSaved = await _context.SaveChangesAsync(cancellationToken);

            _logger.LogInformation("SprintPlan saved successfully. New SprintPlan ID: {SprintPlanId} for Project ID: {ProjectId}. Changes saved: {Changes}", sprintPlan.SprintId, sprintPlan.ProjectId, changesSaved);

            return sprintPlan.SprintId; // Return the auto-generated SprintId
        }
    }
}
