using MediatR;
using Microsoft.AspNetCore.Identity; // Required for RoleManager
using Microsoft.Extensions.Logging;
using EDR.Application.CQRS.Permissions.Commands;
using EDR.Application.Dtos;
using EDR.Domain.Entities;
using EDR.Repositories.Interfaces; // For IPermissionRepository, IUnitOfWork
using EDR.Application.Services.IContract; // For ICurrentUserService, ITenantService
using System;
using System.Collections.Generic; // Added for List
using System.Linq; // Added for Any()
using System.Threading; // Added for CancellationToken
using System.Threading.Tasks;
using EDR.Domain.UnitWork;
// Removed: using EDR.Domain.GenericRepository; // Added for IRepository<T> - not needed if using UnitOfWork directly

namespace EDR.Application.CQRS.Permissions.Handlers
{
    public class CreatePermissionCommandHandler : IRequestHandler<CreatePermissionCommand, int>
    {
        private readonly IPermissionRepository _permissionRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICurrentUserService _currentUserService;
        private readonly ITenantService _tenantService;
        private readonly ILogger<CreatePermissionCommandHandler> _logger;
        private readonly RoleManager<Role> _roleManager; // Inject RoleManager

        public CreatePermissionCommandHandler(
            IPermissionRepository permissionRepository,
            IUnitOfWork unitOfWork,
            ICurrentUserService currentUserService,
            ITenantService tenantService,
            ILogger<CreatePermissionCommandHandler> logger,
            RoleManager<Role> roleManager) // Add RoleManager to constructor
        {
            _permissionRepository = permissionRepository ?? throw new ArgumentNullException(nameof(permissionRepository));
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
            _currentUserService = currentUserService ?? throw new ArgumentNullException(nameof(currentUserService));
            _tenantService = tenantService ?? throw new ArgumentNullException(nameof(tenantService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _roleManager = roleManager ?? throw new ArgumentNullException(nameof(roleManager)); // Assign RoleManager
        }

        public async Task<int> Handle(CreatePermissionCommand request, CancellationToken cancellationToken)
        {
            if (request.PermissionDto == null)
            {
                _logger.LogError("CreatePermissionCommand received null PermissionDto.");
                throw new ArgumentNullException(nameof(request.PermissionDto));
            }

            // Basic validation: Check if a permission with the same name already exists
            var existingPermission = await _permissionRepository.GetByNameAsync(request.PermissionDto.Name);
            if (existingPermission != null)
            {
                _logger.LogWarning($"Permission with name '{request.PermissionDto.Name}' already exists.");
                throw new ArgumentException($"Permission with name '{request.PermissionDto.Name}' already exists.");
            }

            var permission = new Permission
            {
                Name = request.PermissionDto.Name,
                Description = request.PermissionDto.Description,
                Category = request.PermissionDto.Category
                // Note: Id is generated by the database
            };

            var createdPermissionId = await _permissionRepository.AddAsync(permission);
            _logger.LogInformation($"Permission created successfully with ID: {createdPermissionId}");

            // Handle Role Permissions mapping using generic repositories from UnitOfWork
            if (request.PermissionDto.Roles != null && request.PermissionDto.Roles.Any())
            {
                // Get generic repository for RolePermission
                var rolePermissionRepository = _unitOfWork.GetRepository<RolePermission>();

                foreach (var roleDto in request.PermissionDto.Roles)
                {
                    // Validate if the role exists using RoleManager
                    var role = await _roleManager.FindByIdAsync(roleDto.Id); // Use RoleManager to find role by string ID
                    if (role != null)
                    {
                        // Create RolePermission entity
                        var rolePermission = new RolePermission
                        {
                            RoleId = role.Id, // Use the actual Role ID (string) from the found role entity
                            PermissionId = createdPermissionId,
                            // Other properties if needed, e.g., TenantId, CreatedBy, etc.
                        };
                        await rolePermissionRepository.AddAsync(rolePermission);
                        _logger.LogInformation($"Mapped permission {createdPermissionId} to role {role.Id}");
                    }
                    else
                    {
                        _logger.LogWarning($"Role with ID '{roleDto.Id}' not found. Skipping mapping for this role.");
                        // Optionally, throw an exception or handle this case as per requirements
                    }
                }
            }

            await _unitOfWork.SaveChangesAsync(); // Save all changes, including new RolePermission entries

            return createdPermissionId;
        }
    }
}

